### ISSUE TITLE
Won't work with inline lua code

### ISSUE THREAD

**Issue by totallyunknown** [vasilevich/nginxbeautifier#3]
```
location /info.json {

    default_type 'application/json';
    add_header 'Access-Control-Allow-Origin' '*';
    keepalive_timeout 0;

    if ($request_method = 'OPTIONS') {
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Methods' 'GET';
        add_header 'Content-Type' 'text/plain charset=UTF-8';
        add_header 'Content-Length' 0;
        return 204;
    }

    content_by_lua_block {
       ngx.say('{"version": "NGINXSERVERVERSION"}')
    }
}
```

Content like this produce the following error:

```
Working on file: nginx/common/info.conf
/Users/nils/foo/node_modules/nginxbeautifier/nginxbeautifier.js:143
        return input.match(catchRegex)[1];
                                      ^

TypeError: Cannot read property '1' of null
    at extractTextBySeperator (/Users/nils/exaring/edge-cache/node_modules/nginxbeautifier/nginxbeautifier.js:143:39)
    at extractAllPossibleText (/Users/nils/exaring/edge-cache/node_modules/nginxbeautifier/nginxbeautifier.js:162:29)
    at strip_line (/Users/nils/exaring/edge-cache/node_modules/nginxbeautifier/nginxbeautifier.js:193:29)
    at clean_lines (/Users/nils/exaring/edge-cache/node_modules/nginxbeautifier/nginxbeautifier.js:219:46)
    at Object.<anonymous> (/Users/nils/exaring/edge-cache/node_modules/nginxbeautifier/nginxbeautifier.js:530:22)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
```

**Comment by vasilevich** [comment]
Hi, thanks for reporting I will check shortly.

**Comment by vasilevich** [comment]
Hey, thank you for your patience, I believe I have fixed the problem in the following commit, please reopen, or open a new issue if another problem arise.

best of luck!
